### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by emsifa** [emsifa/stuble#11]
Create unit tests for every classes and commands. Also setup automate test and coverage action on push and pull request.

## Tasks

- [ ] Test `Emsifa\Stuble\Stuble` class.
- [ ] Test `Emsifa\Stuble\Stub` class.
- [ ] Test `Emsifa\Stuble\Stub` class.
- [ ] Test `Emsifa\Stuble\Parser` class.
- [ ] Test `Emsifa\Stuble\Helper` class.
- [ ] Test `Emsifa\Stuble\Gitignore` class.
- [ ] Test `Emsifa\Stuble\Filters` class.
- [ ] Test `make` command.
- [ ] Test `ls` command.
- [ ] Setup GitHub action to run tests and push coverage data to codecov.io
